inc/mavlinktelemetry.h
qml/main.qml
qml/ui/AppSettingsPanel.ui.qml
qml/ui/widgets/HorizonWidget.qml
qml/ui/widgets/HorizonWidgetForm.ui.qml
src/mavlinktelemetry.cpp

In Mavlink telemetry breaks were missing so pitch and roll were not being evaluated correctly. All other breaks fixed.
Horizon pitch and roll added
Horizon now depicted as 2 rects
Horizon is added to app settings
Horizon is called in main. You probably want to fix or change that

Mavlink Telemetry fix. Horizon Added

---

inc/openhd.h
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/HUDOverlayGrid.qml
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/widgets/ArrowWidgetForm.qml
qml/ui/widgets/HeadingWidgetForm.ui.qml
qml/ui/widgets/MapWidget.qml
qml/ui/widgets/MapWidgetForm.ui.qml
qml/ui/widgets/SpeedWidgetForm.ui.qml

Added experimental map display. Untested.
Blue center is 1m and the red transparent circle shows hdop.

Map Display and other widget changes

---

qml/qml.qrc
qml/ui/StatusPanelForm.ui.qml
qml/ui/elements/ColoredCheckbox.qml
qml/ui/elements/ColoredCheckboxForm.ui.qml
src/main.cpp

There is no defined time scale for the X axis, but for the moment that is OK as the charts are primarily intended to show a recent snapshot rather than a specific time period. We can add full time support later on.
These may have an effect on rendering which would require disabling them when they aren't visible.

Add telemetry charts in status panel

---

inc/openhd.h
qml/main.qml
qml/ui/AppSettingsPanel.ui.qml
qml/ui/widgets/AirBatteryWidgetForm.ui.qml
qml/ui/widgets/AirStatusWidgetForm.ui.qml
qml/ui/widgets/AltitudeSecondWidgetForm.ui.qml
qml/ui/widgets/AltitudeWidgetForm.ui.qml
qml/ui/widgets/ArrowWidgetForm.qml
qml/ui/widgets/BitrateWidgetForm.ui.qml
qml/ui/widgets/DownlinkRSSIWidgetForm.ui.qml
qml/ui/widgets/FlightModeWidgetForm.ui.qml
qml/ui/widgets/FlightTimerWidgetForm.ui.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
qml/ui/widgets/GPSWidgetForm.ui.qml
qml/ui/widgets/GroundPowerWidgetForm.ui.qml
qml/ui/widgets/GroundStatusWidgetForm.ui.qml
qml/ui/widgets/HeadingWidgetForm.ui.qml
qml/ui/widgets/HomeDistanceWidgetForm.ui.qml
qml/ui/widgets/HorizonWidgetForm.ui.qml
qml/ui/widgets/MapWidgetForm.ui.qml
qml/ui/widgets/SpeedWidgetForm.ui.qml
qml/ui/widgets/ThrottleWidgetForm.ui.qml
qml/ui/widgets/UplinkRSSIWidgetForm.ui.qml
qml/ui/widgets/VideoWidgetForm.ui.qml
src/mavlinktelemetry.cpp
src/openhd.cpp

hud updates

---

QOpenHD.pro
ios/Info.plist
qml/main.qml
qml/qml.qrc
qml/ui/elements/MapComponent.qml
qml/ui/widgets/BaseWidget.qml
qml/ui/widgets/BaseWidgetForm.ui.qml
qml/ui/widgets/MapWidget.qml
qml/ui/widgets/MapWidgetForm.ui.qml

This PR merges the small and large map instances so that there is just one, which significantly simplifies dealing with the map itself.
Also adds a way for widgets to signal that they want to be drag-and-dropped using a small grab point instead of the entire widget, which frees up the widget itself for all touch interaction.

Merge small and large maps

---

inc/openhd.h
qml/main.qml
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/widgets/VibrationWidget.qml
qml/ui/widgets/VibrationWidgetForm.ui.qml
src/mavlinktelemetry.cpp
src/openhd.cpp

Clipping is exposed but not used.. If demanded another display could be added to show clipping

Vibration Widget. Also expose Clipping but unused at this time.

---

inc/openhd.h
qml/main.qml
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/widgets/VsiWidget.qml
qml/ui/widgets/VsiWidgetForm.ui.qml
src/mavlinktelemetry.cpp
src/openhd.cpp

A small additional probably unnecessary declaration was added for vibration widget... Was missing from last pr..

OSD vsi display

---

inc/openhd.h
qml/main.qml
qml/ui/widgets/AirBatteryWidgetForm.ui.qml
qml/ui/widgets/ControlWidgetForm.ui.qml
qml/ui/widgets/DownlinkRSSIWidgetForm.ui.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
src/mavlinktelemetry.cpp
src/openhd.cpp

In an effort to decrease cpu use the math done in java has been moved to c++.

Fpv widget math moved to c++

---

inc/openhd.h
qml/main.qml
qml/ui/widgets/FlightMahWidgetForm.ui.qml
src/mavlinktelemetry.cpp
src/openhd.cpp

Total Mah runs all the time and switched to QElapsedTimer 

---

inc/openhd.h
qml/main.qml
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/widgets/FcTempWidget.qml
qml/ui/widgets/FcTempWidgetForm.ui.qml
qml/ui/widgets/FlightDistanceWidgetForm.ui.qml
qml/ui/widgets/GPSWidgetForm.ui.qml
qml/ui/widgets/RcRSSIWidgetForm.ui.qml
src/mavlinktelemetry.cpp
src/openhd.cpp

I missed a couple glow issues that I spotted later...

More Glow Cleanup. FC Temp Widget. Default flight Mode 

---

inc/altitudeladder.h
inc/headingladder.h
inc/speedladder.h

Also a test of my squeeky clean new repo ;)

Remove QML_ELEMENT lines

---

inc/altitudeladder.h
inc/headingladder.h
inc/speedladder.h
qml/main.qml
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/elements/MapComponent.qml
qml/ui/widgets/AltitudeWidgetForm.ui.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
qml/ui/widgets/HeadingWidgetForm.ui.qml
qml/ui/widgets/HorizonWidgetForm.ui.qml
qml/ui/widgets/SpeedSecondWidget.qml
qml/ui/widgets/SpeedSecondWidgetForm.ui.qml
qml/ui/widgets/SpeedWidgetForm.ui.qml
qml/ui/widgets/WindWidgetForm.ui.qml
src/altitudeladder.cpp
src/headingladder.cpp
src/speedladder.cpp

I might tack on a few more things in this commit if there is time... but dont delay for me

Replace HDG canvas. Ladder tweaks. Horizon bar tweaks

---

qml/MainVideoAndroid.qml
qml/MainVideoGStreamer.qml
qml/MainVideoRender.qml
qml/ui/AppSettingsPanel.ui.qml
qml/ui/GroundPiSettingsPanelForm.ui.qml
qml/ui/elements/StatusChartForm.ui.qml
qml/ui/widgets/AdsbWidgetForm.ui.qml
qml/ui/widgets/BlackBoxWidgetForm.ui.qml
qml/ui/widgets/ExampleWidgetForm.ui.qml
qml/ui/widgets/FcTempWidgetForm.ui.qml
qml/ui/widgets/GPSWidgetForm.ui.qml
qml/ui/widgets/MapWidgetForm.ui.qml
qml/ui/widgets/RcRSSIWidgetForm.ui.qml
qml/ui/widgets/RollWidgetForm.ui.qml
qml/ui/widgets/UplinkRSSIWidgetForm.ui.qml
qml/ui/widgets/VibrationWidgetForm.ui.qml
qml/ui/widgets/VideoWidgetRenderForm.ui.qml

Also a minor cleanup of my deleted servo widget

Qstr added to text where missing

---

src/horizonladder.cpp

A fix to how the horizon pitch lines would exceed 90 degrees on the viewable pitch lines (ladder)

Fix to Horizon Wrap at extreme pitch

---

qml/ui/SettingsPopupForm.ui.qml

MInor fix so that charts option is visible when the build directive is changed

Wired charts visibility to build variable

---

qml/ui/elements/MapComponent.qml

This file did not make it in the last merge.. It should have been in that set.

Switch out airplane icon image for c++

---

inc/drawingcanvas.h
qml/ui/elements/MapComponent.qml
src/ADSBVehicleManager.cpp
src/drawingcanvas.cpp

Added the speed tail back to the icon. Dont add adsb sdr traffic with 0.0 lat or lon

Ongoing ADSB efficiency improvements

---

inc/ADSBVehicleManager.h
qml/ui/elements/AppSettings.qml
qml/ui/widgets/AdsbWidgetForm.ui.qml
src/ADSBVehicleManager.cpp

Slider now controls both opensky and sdr adsb. Also shows max range in km next to slider

Add more controllable max distance for adsb

---

src/ADSBVehicleManager.cpp

Left the clear and delete method in place for future use but its not called. App seemed to be leaking memory using only clear and delete

Revert TESTING of clearing and deleting model

---

inc/horizonladder.h
qml/ui/widgets/HorizonWidgetForm.ui.qml
src/horizonladder.cpp

Horizon widget updated with new parameters
Space: Space between lines
Range: Total range in degrees
Step: Degrees between lines

Updated Horizon widget with more settings

---

qml/ui/widgets/FlightModeWidgetForm.ui.qml
qml/ui/widgets/HomeDistanceWidgetForm.ui.qml
qml/ui/widgets/MissionWidgetForm.ui.qml
qml/ui/widgets/ThrottleWidgetForm.ui.qml
src/horizonladder.cpp
src/mavlinktelemetry.cpp

I was trying to detect autopilot type by sending request to FC but it wasnt reliable... So only a text warning for inav users. Wont do anything as Inav does not support thee mavlink features

Dont limit cmds to Ardupilot

---

inc/altitudeladder.h
inc/horizonladder.h
inc/openhd.h
qml/qtquickcontrols2.conf
qml/ui/elements/AppSettings.qml
qml/ui/widgets/AltitudeWidgetForm.ui.qml
qml/ui/widgets/HeadingWidgetForm.ui.qml
qml/ui/widgets/HorizonWidgetForm.ui.qml
qml/ui/widgets/VibrationWidgetForm.ui.qml
src/altitudeladder.cpp
src/headingladder.cpp
src/horizonladder.cpp
src/openhd.cpp

Altitude and Vibration widget uses now same font as others
Size of horizon changed to double to get it smother
Tweaking of horizon to avoid painting on top of each other

Update of widgets

---

qml/ui/widgets/BaseWidgetForm.ui.qml
qml/ui/widgets/MapWidget.qml

Fix issue with map dropdown on Linux
Issue was automatically handled in apple devices
Changed y-grid of action widgets to have 3 positions

Fix issue with map dropdown

---

qml/ui/elements/AppSettings.qml
qml/ui/widgets/BaseWidget.qml
qml/ui/widgets/BaseWidgetForm.ui.qml
qml/ui/widgets/MapWidget.qml
qml/ui/widgets/MapWidgetForm.ui.qml

Hides detailed window until dragging has finnished
Background color of settings window changed to grey for visibility

Hide detailed Window while dragging

---

qml/ui/widgets/BaseWidgetForm.ui.qml
qml/ui/widgets/MapWidget.qml
qml/ui/widgets/MapWidgetForm.ui.qml

Fixed issue when moving from full size to small size
Changed from scaling window to resize which keep resolution of content

Fixed resize of map issue

---

package.sh

Add the SDL2 libraries for RC in QOPENHD

SDL2 Packages

---

qml/main.qml
src/mavlinkbase.cpp

The window on top flag doesnt seem to be recognised by some platforms. It also creates problems not having a window on some platforms. COmmented out so if someone wants to play with it later its there but right now dont really need it.

Functionality to enable rc and comment out window on top

---

qml/ui/AppSettingsPanel.ui.qml
qml/ui/elements/AppSettings.qml
qml/ui/widgets/AltitudeWidgetForm.ui.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
qml/ui/widgets/HeadingWidgetForm.ui.qml
qml/ui/widgets/HorizonWidgetForm.ui.qml
qml/ui/widgets/RollWidgetForm.ui.qml
qml/ui/widgets/SpeedWidgetForm.ui.qml
qml/ui/widgets/VsiWidgetForm.ui.qml
qml/ui/widgets/WindWidgetForm.ui.qml

Cherry picked from master branch.. untested on 2.0 branch

Data smoothing/animation for widgets

---

src/openhdvideostream.cpp

Added H265 decoding pipeline with OSD overlay

H265 decoding pipeline with OSD overlay

---

QOpenHD.pro
qml/main.qml
qml/ui/AppSettingsPanel.ui.qml
src/openhdvideostream.cpp

Link microservice for link is enabled for all platforms but has no functionality yet

Background Transparency, hot restart for h264 switch, enable link microservice

---

qml/main.qml
qml/ui/AppSettingsPanel.ui.qml
qml/ui/elements/AppSettings.qml

This should make OSD more usable in goggles

Stereo OSD scale and X position options in Video tab

---

src/ADSBVehicleManager.cpp
src/gpiomicroservice.cpp
src/linkmicroservice.cpp
src/localmessage.cpp
src/main.cpp
src/mavlinktelemetry.cpp
src/openhdsettings.cpp
src/openhdtelemetry.cpp
src/statusmicroservice.cpp
src/util.cpp

This is not entirely comprehensive. There might still be a few places that its appropriate to make this addition

Add jetson as ground flag & sysid 226

---

src/openhdsettings.cpp

I had misnamed general.template, general.conf in my dev env and didnt correct it when it was pushed the first time. Also screwed up missing "ground" in the path for the conf files

Corrected the file path from dev to sbc environment

---

app/exp/avcodec_decoder.cpp

Fixes https://github.com/OpenHD/QOpenHD/issues/350

Fix avformat const conversion
