qml/ui/widgets/AltitudeSecondWidgetForm.ui.qml
qml/ui/widgets/AltitudeWidgetForm.ui.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
qml/ui/widgets/HeadingWidgetForm.ui.qml
qml/ui/widgets/SpeedWidgetForm.ui.qml

All widgets I touched have the appropriate "widgetInner" id. Everything tested and wiggles!
Added "widgetGlyph" consistently across applicable widgets as a naming convention

Fixed item names with widgetInners

---

inc/openhdsettings.h
qml/ui/GroundPiSettingsPanel.ui.qml
qml/ui/SettingsPopup.qml
qml/ui/SettingsPopupForm.ui.qml
src/openhdsettings.cpp

This shows a "Saved" message next to the save button in settings once the ground station confirms that the settings were actually saved by sending back a "SavedGround" reply.
The message is displayed for 5 seconds and then removed.
There is also code in this PR to show a failure message, currently routed to the on-screen log but another small message could be added to the settings panel itself in the same place the "Saved" message appears.

Add save settings indicator

---

QOpenHD.pro
inc/openhdmmalrender.h
inc/openhdmmalvideo.h
inc/openhdvideo.h
qml/MainVideoMMAL.qml
qml/main.qml
qml/qml.qrc
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/widgets/VideoWidget.qml
qml/ui/widgets/VideoWidgetMMALForm.ui.qml
src/main.cpp
src/openhdmmalrender.cpp
src/openhdmmalvideo.cpp
src/openhdvideo.cpp

This uses the MMAL API to decode incoming h264 NAL units, then sends
them to a standard [QML VideoOutput](https://doc.qt.io/qt-5/qml-qtmultimedia-videooutput.html) rendering system using `QVideoFrame`.
At the moment there is an extra `memcpy()` step, for PiP it won't be
an issue but for 1080p high frame rate it might. There is a way to
feed the decoded buffers directly into a QAbstractVideoBuffer, either
with raw YUV data or a GL texture, and code to handle that is being
tested separately.
This completely replaces GStreamer on the ground station, we no longer
need to use or package it for QOpenHD.

Add MMAL decoder/renderer for Raspberry Pi

---

inc/openhdmmalrender.h
inc/openhdvideo.h
src/openhdmmalrender.cpp
src/openhdmmalvideo.cpp
src/openhdvideo.cpp

This uses the Qt abstract video buffer system to give QML VideoOutput access to the MMAL buffer header data payload, without requiring a memcpy() step which is quite painful even on a pi4.
We also need to automatically handle h264 stream changes such as resolution changes, which can happen at any time. The decoder will let us know when this happens but we have to tear down the output port pool and recreate it using the correct frame size to ensure the new frames will fit.
Because we are giving Qt an MMAL buffer header to hold on to in `MMALPixelBufferVideoBuffer` during rendering, we have to guarantee that it will be released back to the pool before we tear it down during a stream resolution change. This occurs in the destructor in `MMALPixelBufferVideoBuffer`, but to ensure this actually …

Implement zero-copy rendering on Pi, handle dynamic stream resolution changes

---

qml/qml.qrc

Windwidget missing from qrc file

Qrc Windwidget missing

---

qml/main.qml
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/widgets/ArrowWidgetForm.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
qml/ui/widgets/RollWidget.qml
qml/ui/widgets/RollWidgetForm.ui.qml

Fpv glow was being applied slightly ahead of the rotation of the widget. So it appeared that there were two fpv widgets with one lagging behind the first. Got rid of glow and used text outline. We might consider this for all text/glyphs                 
style: Text.Outline
styleColor: settings.color_glow

Bank Angle Widget. Fpv glow fix

---

qml/ui/widgets/DownlinkRSSIWidgetForm.ui.qml
qml/ui/widgets/FcTempWidgetForm.ui.qml
qml/ui/widgets/UplinkRSSIWidgetForm.ui.qml

Just asthetics. But the uplink rssi widget text was noticably smaller. I made it bigger to match the downlink. I cleaned up some of the spacing internally to both widgets

Rssi Downlink and Uplink widget font and spacing matchup

---

QOpenHD.pro
inc/adsb.h
qml/ui/elements/AppSettings.qml
qml/ui/elements/MapComponent.qml
qml/ui/widgets/AdsbWidgetForm.ui.qml
src/adsb.cpp
src/main.cpp
src/markermodel.cpp
src/openhd.cpp

Both sdr and api sources are now under one class called adsb. Both ways make network requests against json sources. 
SDR is getting its data across the local network of the ground pi hard coded at 192.168.2.1. The groundpi runs dump1090 to parse the sdr adsb messages and then the resulting json is disseminated via lighttpd server on the groundpi. Lighttpd and dump1090 are controlled by a service on the groundpi. This has only been tested via devices running this code on linux and android connecting via hotspot to the groundpi. USB NEEDS TESTING. Need to test on groundpi itself (maybe the addr should be "localhost")
OpenSky is just polling the opensky api... A bound box is applied to limit the results and the bounds are depicted on the map
TODO 
-remove markers when switching between …

ADSB SDR and OpenSky

---

inc/flightpathvector.h
inc/openhd.h
qml/ui/elements/AppSettings.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
src/flightpathvector.cpp
src/main.cpp
src/mavlinktelemetry.cpp
src/openhd.cpp

Completely in C. Stephen measured the cpu consumption to be at 7 percent so a relatively minor improvement. Notable changes are that the flight path vector is actual now and references the horizon widget so it moves per pitch ladder changes and heading ladder changes. IE if the vertical angle of the vehicle is 20 degrees above horizon, the fpv will be on the 20 degree line. The same is true for heading on the horizon- if the vehicle has a crosswind or is moving sideways then the fpv will move laterally to accurately reflect which heading the vehicle is actually moving on ( course vs track). 
Other notable change is that this widget no longer uses a transformation to change size. Size changes are handled within C- might consider attempting this on other widgets to decrease cpu usage.

Flight Path Vector Refactor from qml to C

---

src/adsb.cpp

Apparently QNetworkRequests creates a QNetworkReply object in each request and it is our responsibility to delete it with deleteLater(), otherwise we have memory leak there.

adsb.cpp: Delete reply from QNetworkRequest answer

---

src/adsb.cpp

In the previous commit we forgot to call
deleteLater() in the return cases within
the slot

adsb.cpp: Delete reply from QNetworkRequestManager in all cases:

---

qml/ui/widgets/MapWidget.qml

As the component.createObject was only created if component.status == ready we were not able to see regular qml debug info for MapComponent.qml.
This commit adds an else statement and outputs component.errorString() on console.log(), so if MapComponent.qml had any trouble loading we can see the regular qml debug info.

MapWidget.qml: Add debug info for failed map creation

---

QOpenHD.pro
inc/ADSBVehicle.h
inc/ADSBVehicleManager.h
inc/QmlObjectListModel.h
inc/mavlinktelemetry.h
qml/main.qml
qml/ui/elements/AppSettings.qml
qml/ui/elements/MapComponent.qml
qml/ui/widgets/AdsbWidgetForm.ui.qml
src/ADSBVehicle.cpp
src/ADSBVehicleManager.cpp
src/QmlObjectListModel.cpp
src/main.cpp
src/mavlinktelemetry.cpp
src/openhd.cpp

This is a bit of a monster PR. The initial idea was to only implement mavlink adsb support, but the older adsb implementation relied on a list deleted and generated again for each call to the apis. Mavlink by ADSB unfortunately is coming as a message for each vehicle information, so it would have been a mess to integrate this with the older implementation. A lot of this code is slightly modified code from QGroundControl.
First of all, I ported the QmlObjectListModel from QGC. This is a class derived from qabstractlistmodel, for instantiating stuff that must be exposed to qml. It is super handy for representing objects in QML from cpp, and it can be reusable multiple times as it is not bound to specific type of data, as our markermodel were. So for instance this class could be reused for …

Rework of adsb implementation

---

QOpenHD.pro
inc/mavlinkbase.h
inc/mavlinktelemetry.h
inc/missionwaypoint.h
inc/missionwaypointmanager.h
inc/openhd.h
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/HUDOverlayGridForm.ui.qml
qml/ui/elements/AppSettings.qml
qml/ui/elements/MapComponent.qml
qml/ui/widgets/AirBatteryWidgetForm.ui.qml
qml/ui/widgets/HomeDistanceWidgetForm.ui.qml
qml/ui/widgets/MapWidgetForm.ui.qml
qml/ui/widgets/MissionWidget.qml
qml/ui/widgets/MissionWidgetForm.ui.qml
qml/ui/widgets/ThrottleWidgetForm.ui.qml
qml/ui/widgets/VROverlayForm.ui.qml
src/main.cpp
src/mavlinkbase.cpp
src/mavlinktelemetry.cpp
src/missionwaypoint.cpp
src/missionwaypointmanager.cpp
src/openhd.cpp

This adds a widget which allows the request of mission waypoints from the FC. This widget also displays the total number of mission waypoints and the current mission waypoint. On the map the waypoints are displayed as numbered icons connected by a polyline. There may be some bug with the polyline after repeated waypoint requests. Also some waypoints the FC returns have lat lon values of 0,0. The code currently filters out these 0,0 lat lons while factoring in if they have a relevant command  id number.
Other minor changes were to remove blackbox from the default build setting. VR widget removed the race course...

Mission waypoints widget and map display, some vr cleanup

---

qml/ui/GroundPiSettingsListView.ui.qml
qml/ui/GroundPiSettingsPanel.qml
qml/ui/delegates/BoolSwitchSettingDelegate.ui.qml

I did not realise that the Bool itemType was using the SwitchSettingDelegate when I changed it for the switch itemType. I have added one specific for Bool as they need to be functioning differently. This also makes it a bit more obvious for future changes.

Add BoolSwitchSettingDelegate

---

QOpenHD.pro
inc/ADSBVehicleManager.h
inc/vroverlay.h
qml/ui/AppSettingsPanel.ui.qml
src/ADSBVehicleManager.cpp
src/main.cpp
src/vroverlay.cpp

Some adsb processes were still running after gui controls had changed status. This was generating erroneous "adsb reply error" messages. In addidtion when show adsb widget was selected off, the adsb code would still allow internet or sdr data to flow.
At this time the VR widget is suspected of causing crashes on the pi when large numbers of adsb traffic create a corresponding large number of vr overlay object. THE BOTTOM LINE is that the vr overlay code needs to be re-written. It constantly creates vr-overlay objects instead of using pointers and/or re-using objects.

Bug fixes to ADSB and disable VR widget

---

QOpenHD.pro
inc/logger.h
inc/logger_t.h
src/ADSBVehicleManager.cpp
src/logger.cpp
src/main.cpp

This is the foundation of a data logger. It is far from perfect right now because it opens and closes the log file continuously as it appends. It also does not handle all build platforms due to differences in path to a log file and permissions etc. Finally, the build directive is a little messy for turning it off and on. 
As of now for rpi the log file will be created in /boot/QOpenHD-Log.txt
For linux and android /tmp/QOpenHD-Log.txt
Windows is an untested location
Mac/IOS there is no location and if logging is enabled it will almost certainly crash the app (comments added)
For now this logger is an attempt to find the reason behind ADSB crashing, thus the adsb logger calls.
In the future ,after the obvious improvements to the logger are made, this logger scheme could be expanded to …

Data Logger and Debug statements for ADSB

---

inc/logger.h
src/logger.cpp

Now the logger opens the file in "init" from there it passes a pointer to the logging data method. The log file never gets closed though..

Fix Logger being opened and closed upon every write

---

inc/mavlinkbase.h
src/mavlinkbase.cpp
src/mavlinktelemetry.cpp

This is part of an effort to provide a way to identify inav vs ardupilot. Right now the request is fired off at the same time we set_data_stream . Both are based on the receipt of the first sys_time message being received. Makes sense as then we know there is an actual FC talking to us

Autopilot info request

---

inc/mavlinktelemetry.h
qml/ui/PowerPanelForm.ui.qml
qml/ui/widgets/FlightModeWidgetForm.ui.qml
qml/ui/widgets/HomeDistanceWidgetForm.ui.qml
qml/ui/widgets/MissionWidgetForm.ui.qml
qml/ui/widgets/ThrottleWidgetForm.ui.qml
src/ADSBVehicleManager.cpp
src/logger.cpp
src/mavlinkbase.cpp
src/mavlinktelemetry.cpp

Logger now writes to a txt file in the log for the pi
Now it only recognises arucopter or arduplane if autopilot version is greater than 999. If its not arduplane or arducopter actions/commands for throttle arming, flight mode change, return to land, and mission waypoints is hidden and a message displays in the popup with "only ardupilot commands supported". SORRY INAV GUYS- mavlink is a downlink only except for rc override as of version 3.0.1

Bug fixes to logger and inav not being detected

---

QOpenHD.pro
inc/drawingcanvas.h
src/drawingcanvas.cpp
src/main.cpp

This is the start of an effort to make the map display more efficient. We should avoid images as much as possible on the map, especially in situations where its duplicated.
This commit puts the airplane icon into C. In C it draws the airplane from a glyph. There might be more efficient ways to draw it in C. 
Right now the contrail of the airplane is gone needs to be added back. Ultimately the info blurb needs to be put into C as well.

Switch airplane icon on map to C

---

inc/ADSBVehicle.h
inc/ADSBVehicleManager.h
src/ADSBVehicle.cpp
src/ADSBVehicleManager.cpp

On going attempt to test the limits of the combination of adsb sdr and pi3b.. As the title says- the time interval for refreshes of the adsb sdr refreshes within the app went from 1000ms to 2000ms. The looping through all adsb traffic in order to delete stale vehicles went from every 1000ms to 4500ms.
Perhaps most significantly, a check was added to only add new adsb traffic that was within 20 km ( roughly match the max bound box for opensky adsb). Also if the vehicle already exists in the model and goes beyond the 20km distance it gets deleted (same process as cleanup stale)

ADSB- SDR time 2s, cleanup 4.5, limit distance 20km

---

QOpenHD.pro
inc/drawingcanvas.h
qml/ui/elements/MapComponent.qml
qml/ui/widgets/AdsbWidgetForm.ui.qml
src/ADSBVehicleManager.cpp
src/drawingcanvas.cpp
src/main.cpp

Both internet and sdr adsb json parsers look for "null" entries and other various error checks to avoid the map seeing a null model output( in mapcomponent object.altitude was the worse) . Migration of the adsb icon to c++ is complete now. 
There was a strange bug where sometimes a null value was seen on object.altitude in the map component when multiple references to object.altitude were used. Still unexplained but is gone now.
The adsb glyph is still broken in the pi. We also lost the climb or descend arrow displayed for each adsb traffic- can be added back later

ADSB parser error checking. Cleanup of ADSB map component

---

qml/ui/widgets/BaseWidgetForm.ui.qml
qml/ui/widgets/MapWidgetForm.ui.qml

Fixes an issue that happens when OpenStreet map is selected on iOS devices.
QT seems to have issues when animation is shaking the map and at the same time moving the widget
Widget settings window is moved to always be in bottom part of screen and opposite side to the widget itself

Fixes iOS crashes moving OpenStreet map and update widget settings view

---

qml/ui/elements/MapComponent.qml
qml/ui/widgets/BaseWidget.qml
qml/ui/widgets/BaseWidgetForm.ui.qml
qml/ui/widgets/MapWidget.qml
qml/ui/widgets/MapWidgetForm.ui.qml

Fixes:
- OpenStreetMap does not support satellite as we use it, added handling when variant options changes
- Allow gestures after change of map provider
- Prevent the ability to move widgets out of screen
- Position action window on a 5x5 grid

Fixes map crashes with OpenStreet + avoid dragging widgets off screen

---

qml/ui/widgets/GroundStatusWidgetForm.ui.qml

Ground status widget had the wrong mapping for settings to change colour of based on temp or cpu.

Fix incorrect mapping for colour change.

---

QOpenHD.pro
inc/mavlinkbase.h
inc/mavlinktelemetry.h
inc/openhdrc.h
qml/qml.qrc
qml/ui/AppSettingsPanel.ui.qml
qml/ui/RcPanel.qml
qml/ui/RcPanelForm.ui.qml
qml/ui/SettingsPopupForm.ui.qml
qml/ui/elements/AppSettings.qml
qml/ui/widgets/AltitudeWidgetForm.ui.qml
qml/ui/widgets/FpvWidgetForm.ui.qml
qml/ui/widgets/HeadingWidgetForm.ui.qml
qml/ui/widgets/HorizonWidgetForm.ui.qml
qml/ui/widgets/RollWidgetForm.ui.qml
qml/ui/widgets/SpeedWidgetForm.ui.qml
qml/ui/widgets/VsiWidgetForm.ui.qml
qml/ui/widgets/WindWidgetForm.ui.qml
src/main.cpp
src/mavlinkbase.cpp
src/mavlinktelemetry.cpp
src/openhdrc.cpp
src/openhdvideostream.cpp

Stephens version of mavlink RC is commented out in relevant parts. It was never tested as I did not know it was even there until after I did my own version. My version seems a little more verbose and it has its own method of sending RC rather than Stephens which expanded on the existing "command" method. 
Joystick axis button view in settings now there.
Animation smoothing via behavior and duration. Controlled by a setting in widgets. There is no "off" switch but you can dial animation smoothing to "0" and in effect have it off. Cpu usage might need to be observed to see how its affected. It only interpolates data before its sent to the drawing in C. The assumption is that cpu will be unnaffected

RC Mavlink (Stephen Version disabled) and Animation Smoothing

---

qml/main.qml
qml/ui/AppSettingsPanel.ui.qml
qml/ui/elements/AppSettings.qml
src/mavlinktelemetry.cpp

App background can now be set transparent or black (default) . ALSO had some comments left over from rc testing in sitl that defines a local ip addr for the groundstation. The comments were removed and only for the pi will ground station be defined. This reveals implications for other groundstations like the jetson where it needs to be added as a platform

App Background setting & groundpi ip defined (was for sitl tests)

---

inc/mavlinktelemetry.h

Without these flags the autogenerated moc_mavlink_telemetry.cpp file was creating errors when RC was disabled

More RC compiler Flags

---

inc/mavlinkbase.h
inc/openhdrc.h
src/mavlinkbase.cpp
src/openhdrc.cpp

Rc_override messages will start being sent when a joystick is detected present. If there is no joystick no messages will be sent. This should allow failsafe to work correctly if there is a disconnection of the joystick from the groundstation

start/stop RC msg if JS plugged/unplugged

---

inc/mavlinktelemetry.h
qml/ui/elements/AppSettings.qml
qml/ui/widgets/BitrateWidgetForm.ui.qml
qml/ui/widgets/DownlinkRSSIWidgetForm.ui.qml
src/mavlinkbase.cpp
src/mavlinktelemetry.cpp

Not wired to anything except cam brightness does fire off mavlink messages for testing. There is also a commented out freq test button that passes the request a different way (via openhd class) to the mavlink class.

Live settings for wifi, cam, and video- not active

---

qml/ui/widgets/BaseWidgetForm.ui.qml

When repositioning widgets there is a time when the detail popup is not visible so no X position was being generated. This was causing an "undefined" error for that var

Fix error in base widget popup X axis
